apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fs-dev-echo-ip
  name: fs-dev-echo-ip
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fs-dev-echo-ip
  template:
    metadata:
      labels:
        app: fs-dev-echo-ip
    spec:
      containers:
      - image: 192.168.1.10:8443/echo-ip
        name: fs-dev-echo-ip
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1        
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fs-dev-echo-ip
  name: fs-dev-echo-ip-svc
  namespace: dev
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: fs-dev-echo-ip
  type: LoadBalancer
