apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
<<<<<<< HEAD:echo-ip-dev.yaml
    app: fs-echo-ip-dev
  name: fs-echo-ip-dev
=======
    app: fs-dev-echo-ip
  name: fs-dev-echo-ip
>>>>>>> 9a328a192462a56ce0a649e0a02108c88d192696:dev-echo-ip.yaml
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
<<<<<<< HEAD:echo-ip-dev.yaml
      app: fs-echo-ip-dev
  template:
    metadata:
      labels:
        app: fs-echo-ip-dev
    spec:
      containers:
      - image: 192.168.1.10:8443/echo-ip
        name: fs-echo-ip-dev
=======
      app: fs-dev-echo-ip
  template:
    metadata:
      labels:
        app: fs-dev-echo-ip
    spec:
      containers:
      - image: 192.168.1.10:8443/echo-ip
        name: fs-dev-echo-ip
>>>>>>> 9a328a192462a56ce0a649e0a02108c88d192696:dev-echo-ip.yaml
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1        
---
apiVersion: v1
kind: Service
metadata:
  labels:
<<<<<<< HEAD:echo-ip-dev.yaml
    app: fs-echo-ip-dev
  name: fs-echo-ip-dev-svc 
=======
    app: fs-dev-echo-ip
  name: fs-dev-echo-ip-svc
>>>>>>> 9a328a192462a56ce0a649e0a02108c88d192696:dev-echo-ip.yaml
  namespace: dev
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
<<<<<<< HEAD:echo-ip-dev.yaml
    app: fs-echo-ip-dev
=======
    app: fs-dev-echo-ip
>>>>>>> 9a328a192462a56ce0a649e0a02108c88d192696:dev-echo-ip.yaml
  type: LoadBalancer
